version: "3.9"

services:
  app:
    build:
      args:
        user: dev
        uid: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www

  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RedStore
    ports:
      - "5432:5432"

  nginx:
    image: nginx:1.21.6-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
