version: "3.9"

services:
  app:
    build:
      args:
        user: dev
        uid: 1000
        document_root: /var/www/html/public
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
      - "443:443"

  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RedStore
    ports:
      - "5432:5432"
